[theme]
primaryColor = "#00a8ff"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
base = "light"
primaryTextColor = "#000000"
secondaryTextColor = "#666666"
tertiaryTextColor = "#999999"
infoTextColor = "#333333"
successTextColor = "#00cc00"
warningTextColor = "#ffcc00"
dangerTextColor = "#ff0000"
primaryButtonColor = "#00a8ff"
secondaryButtonColor = "#FFFFFF"
primaryButtonTextColor = "#FFFFFF"
secondaryButtonTextColor = "#00a8ff"
primaryHeaderColor = "#00a8ff"
secondaryHeaderColor = "#FFFFFF"
primaryHeaderTextColor = "#FFFFFF"
secondaryHeaderTextColor = "#00a8ff"
primarySidebarColor = "#FFFFFF"
secondarySidebarColor = "#f0f2f6"
primarySidebarTextColor = "#262730"
secondarySidebarTextColor = "#666666"
primaryFooterColor = "#FFFFFF"
secondaryFooterColor = "#f0f2f6"
primaryFooterTextColor = "#262730"
secondaryFooterTextColor = "#666666"
